### ISSUE TITLE
Content-Format support for DER-encoded ASN.1 objects

### ISSUE THREAD

**Issue by malishav** [ace-wg/est-oscore#38]
The draft currently mandates that Content-Format 281 MUST be supported by the server and Content-Format 287 MAY be supported by the server:

> Content-Format 281 MUST be supported by EST-oscore servers. Servers MAY also support Content-Format 287. It is up to the client to support only Content-Format 281, 287 or both.

This is an issue in RFC9148 as it may lead to interoperability issues where clients request/support 287 but server only supports 281.

This issue aims at fixing this in the EST-oscore document.

CC: @EskoDijk

**Comment by malishav** [comment]
@EskoDijk:Has this progressed further in ANIMA in a way that I could reference it from this document? Is there a document you could point me to? 

(I created a PR with the simplest solution to mandate 287 for servers (PR #39) for now, but don't plan on merging it until this is resolved. )

**Comment by EskoDijk** [comment]
@malishav Thanks for looking into this. There's now a new revision of cBRSKI where this issue is addressed, see text in https://datatracker.ietf.org/doc/html/draft-ietf-anima-constrained-voucher#brski-est-extensions-registrar (Section 6.6).

Besides this, cBRSKI also adds in Seciton 6.5.5 a new Content-Format for the /crts resources specifically. See https://datatracker.ietf.org/doc/html/draft-ietf-anima-constrained-voucher#name-multipart-content-format-fo 
This is a simpler/alternative container for multiple certs that uses CBOR-based "multipart-core" instead of PKCS.

I've just created the issue https://github.com/anima-wg/constrained-voucher/issues/295 , seeing that cBRSKI doesn't yet mandate support for 287 but the Pledge does rely on it.
